version: '3.7'

services:
  k4r-distance-matrix-api:
    build:
      context: ./k4r-applications
      dockerfile: ./k4r-distance-matrix-api/Dockerfile
    image: registry.gitlab.com/knowledge4retail/k4r-plugins/k4r-distance-matrix-api/k4r-distance-matrix-api:${CI_COMMIT_TAG:-latest}
